[package]
edition = "2021"
name = "minput-mirror"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rdev = "0.5.1"
serde = "1.0.136"
serde_json = "1.0"
tokio = "1.18.2"
listenfd = "0.5.0"